apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-depl-replicas
  labels:
    app : my-k8s-app
    env: prod
    owner: iaa
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name : cia-web
          image: tomcat:latest
          ports:
            - containerPort: 80